package com.quickblox.qmunicate.service;

public class QBServiceConsts {
    public static final String ADD_FRIEND_ACTION = "add friend action";
    public static final String ADD_FRIENDS_ACTION = "add friendsList action";
    public static final String CHANGE_PASSWORD_ACTION = "change password action";
    public static final String GET_FILE_ACTION = "get file action";
    public static final String LOGIN_ACTION = "login action";
    public static final String LOGOUT_ACTION = "logout action";
    public static final String REMOVE_FRIEND_ACTION = "remove friend action";
    public static final String RESET_PASSWORD_ACTION = "reset password action";
    public static final String SIGNUP_ACTION = "signup action";
    public static final String SOCIAL_LOGIN_ACTION = "social login action";
    public static final String UPDATE_USER_ACTION = "update user action";
    public static final String FRIENDS_LOAD_ACTION = "friends load action";
    public static final String USER_SEARCH_ACTION = "user search action";
    public static final String SEND_MESSAGE_ACTION = "send message action";
    public static final String SEND_GROUP_MESSAGE_ACTION = "send group message action";
    public static final String LOAD_ATTACH_FILE_ACTION = "load_attach_file_action";

    public static final String ADD_FRIEND_SUCCESS_ACTION = "add friend success action";
    public static final String ADD_FRIENDS_SUCCESS_ACTION = "add friendsList success action";
    public static final String ADD_FRIEND_FAIL_ACTION = "add friend fail action";
    public static final String ADD_FRIENDS_FAIL_ACTION = "add friendsList fail action";
    public static final String CHANGE_PASSWORD_SUCCESS_ACTION = "change password success action";
    public static final String CHANGE_PASSWORD_FAIL_ACTION = "change password fail action";
    public static final String GET_FILE_SUCCESS_ACTION = "get file success action";
    public static final String GET_FILE_FAIL_ACTION = "get file fail action";
    public static final String LOGIN_SUCCESS_ACTION = "login success action";
    public static final String LOGIN_FAIL_ACTION = "login fail action";
    public static final String LOGOUT_SUCCESS_ACTION = "logout success action";
    public static final String LOGOUT_FAIL_ACTION = "logout fail action";
    public static final String REMOVE_FRIEND_SUCCESS_ACTION = "remove friend success action";
    public static final String REMOVE_FRIEND_FAIL_ACTION = "remove friend fail action";
    public static final String RESET_PASSWORD_SUCCESS_ACTION = "reset password success action";
    public static final String RESET_PASSWORD_FAIL_ACTION = "reset password fail action";
    public static final String SIGNUP_SUCCESS_ACTION = "signup success action";
    public static final String SIGNUP_FAIL_ACTION = "signup fail action";
    public static final String UPDATE_USER_SUCCESS_ACTION = "update user success action";
    public static final String UPDATE_USER_FAIL_ACTION = "update user fail action";
    public static final String FRIENDS_LOAD_SUCCESS_ACTION = "friends load success_action";
    public static final String FRIENDS_LOAD_FAIL_ACTION = "friends load fail action";
    public static final String USER_SEARCH_SUCCESS_ACTION = "user search success action";
    public static final String USER_SEARCH_FAIL_ACTION = "user search fai action";
    public static final String SEND_MESSAGE_SUCCESS_ACTION = "send message success action";
    public static final String SEND_MESSAGE_FAIL_ACTION = "send message fail action";
    public static final String LOAD_ATTACH_FILE_SUCCESS_ACTION = "load_attach_file_success_action";
    public static final String LOAD_ATTACH_FILE_FAIL_ACTION = "load_attach_file_fail_action";

    public static final String EXTRA_ATTACH_FILE = "attach_file";
    public static final String EXTRA_CHAT_MESSAGE = "chat message";
    public static final String EXTRA_CHAT_OPPONENT_NAME = "chat opponent name";
    public static final String EXTRA_SENDER_CHAT_MESSAGE = "sender chat message";
    public static final String EXTRA_USER = "qb user";
    public static final String EXTRA_ERROR = "error";
    public static final String EXTRA_FRIEND = "friend";
    public static final String EXTRA_FRIENDS = "friends";
    public static final String EXTRA_FILE = "file";
    public static final String EXTRA_SOCIAL_PROVIDER = "social provider";
    public static final String EXTRA_ACCESS_TOKEN = "access token";
    public static final String EXTRA_ACCESS_TOKEN_SECRET = "access token secret";
    public static final String EXTRA_EMAIL = "email";
    public static final String EXTRA_FILE_ID = "file id";
    public static final String EXTRA_PASSWORD = "password";
    public static final String EXTRA_CONSTRAINT = "constraint";

    public static final String SMILE_SELECTED = "smile_selected";
    public static final String JOIN_ROOM_ACTION = "join room action";
    public static final String JOIN_ROOM_SUCCESS_ACTION = "join room success action";
    public static final String JOIN_ROOM_FAIL_ACTION = "join room fail action";
    public static final String GOT_CHAT_MESSAGE = "got_chat_message";
}
