package com.quickblox.q_municate.ui.chats.emoji.emojiTypes;

import com.quickblox.q_municate.ui.chats.emoji.emojiTypes.EmojiObject;

public class Emoji {

    public static final EmojiObject[] DATA_NATURE = new EmojiObject[]{
            EmojiObject.fromCodePoint(0x1f436),
            EmojiObject.fromCodePoint(0x1f43a),
            EmojiObject.fromCodePoint(0x1f431),
            EmojiObject.fromCodePoint(0x1f42d),
            EmojiObject.fromCodePoint(0x1f439),
            EmojiObject.fromCodePoint(0x1f430),
            EmojiObject.fromCodePoint(0x1f438),
            EmojiObject.fromCodePoint(0x1f42f),
            EmojiObject.fromCodePoint(0x1f428),
            EmojiObject.fromCodePoint(0x1f43b),
            EmojiObject.fromCodePoint(0x1f437),
            EmojiObject.fromCodePoint(0x1f43d),
            EmojiObject.fromCodePoint(0x1f42e),
            EmojiObject.fromCodePoint(0x1f417),
            EmojiObject.fromCodePoint(0x1f435),
            EmojiObject.fromCodePoint(0x1f412),
            EmojiObject.fromCodePoint(0x1f434),
            EmojiObject.fromCodePoint(0x1f411),
            EmojiObject.fromCodePoint(0x1f418),
            EmojiObject.fromCodePoint(0x1f43c),
            EmojiObject.fromCodePoint(0x1f427),
            EmojiObject.fromCodePoint(0x1f426),
            EmojiObject.fromCodePoint(0x1f424),
            EmojiObject.fromCodePoint(0x1f425),
            EmojiObject.fromCodePoint(0x1f423),
            EmojiObject.fromCodePoint(0x1f414),
            EmojiObject.fromCodePoint(0x1f40d),
            EmojiObject.fromCodePoint(0x1f422),
            EmojiObject.fromCodePoint(0x1f41b),
            EmojiObject.fromCodePoint(0x1f41d),
            EmojiObject.fromCodePoint(0x1f41c),
            EmojiObject.fromCodePoint(0x1f41e),
            EmojiObject.fromCodePoint(0x1f40c),
            EmojiObject.fromCodePoint(0x1f419),
            EmojiObject.fromCodePoint(0x1f41a),
            EmojiObject.fromCodePoint(0x1f420),
            EmojiObject.fromCodePoint(0x1f41f),
            EmojiObject.fromCodePoint(0x1f42c),
            EmojiObject.fromCodePoint(0x1f433),
            EmojiObject.fromCodePoint(0x1f40b),
            EmojiObject.fromCodePoint(0x1f404),
            EmojiObject.fromCodePoint(0x1f40f),
            EmojiObject.fromCodePoint(0x1f400),
            EmojiObject.fromCodePoint(0x1f403),
            EmojiObject.fromCodePoint(0x1f405),
            EmojiObject.fromCodePoint(0x1f407),
            EmojiObject.fromCodePoint(0x1f409),
            EmojiObject.fromCodePoint(0x1f40e),
            EmojiObject.fromCodePoint(0x1f410),
            EmojiObject.fromCodePoint(0x1f413),
            EmojiObject.fromCodePoint(0x1f415),
            EmojiObject.fromCodePoint(0x1f416),
            EmojiObject.fromCodePoint(0x1f401),
            EmojiObject.fromCodePoint(0x1f402),
            EmojiObject.fromCodePoint(0x1f432),
            EmojiObject.fromCodePoint(0x1f421),
            EmojiObject.fromCodePoint(0x1f40a),
            EmojiObject.fromCodePoint(0x1f42b),
            EmojiObject.fromCodePoint(0x1f42a),
            EmojiObject.fromCodePoint(0x1f406),
            EmojiObject.fromCodePoint(0x1f408),
            EmojiObject.fromCodePoint(0x1f429),
            EmojiObject.fromCodePoint(0x1f43e),
            EmojiObject.fromCodePoint(0x1f490),
            EmojiObject.fromCodePoint(0x1f338),
            EmojiObject.fromCodePoint(0x1f337),
            EmojiObject.fromCodePoint(0x1f340),
            EmojiObject.fromCodePoint(0x1f339),
            EmojiObject.fromCodePoint(0x1f33b),
            EmojiObject.fromCodePoint(0x1f33a),
            EmojiObject.fromCodePoint(0x1f341),
            EmojiObject.fromCodePoint(0x1f343),
            EmojiObject.fromCodePoint(0x1f342),
            EmojiObject.fromCodePoint(0x1f33f),
            EmojiObject.fromCodePoint(0x1f33e),
            EmojiObject.fromCodePoint(0x1f344),
            EmojiObject.fromCodePoint(0x1f335),
            EmojiObject.fromCodePoint(0x1f334),
            EmojiObject.fromCodePoint(0x1f332),
            EmojiObject.fromCodePoint(0x1f333),
            EmojiObject.fromCodePoint(0x1f330),
            EmojiObject.fromCodePoint(0x1f331),
            EmojiObject.fromCodePoint(0x1f33c),
            EmojiObject.fromCodePoint(0x1f310),
            EmojiObject.fromCodePoint(0x1f31e),
            EmojiObject.fromCodePoint(0x1f31d),
            EmojiObject.fromCodePoint(0x1f31a),
            EmojiObject.fromCodePoint(0x1f311),
            EmojiObject.fromCodePoint(0x1f312),
            EmojiObject.fromCodePoint(0x1f313),
            EmojiObject.fromCodePoint(0x1f314),
            EmojiObject.fromCodePoint(0x1f315),
            EmojiObject.fromCodePoint(0x1f316),
            EmojiObject.fromCodePoint(0x1f317),
            EmojiObject.fromCodePoint(0x1f318),
            EmojiObject.fromCodePoint(0x1f31c),
            EmojiObject.fromCodePoint(0x1f31b),
            EmojiObject.fromCodePoint(0x1f319),
            EmojiObject.fromCodePoint(0x1f30d),
            EmojiObject.fromCodePoint(0x1f30e),
            EmojiObject.fromCodePoint(0x1f30f),
            EmojiObject.fromCodePoint(0x1f30b),
            EmojiObject.fromCodePoint(0x1f30c),
            EmojiObject.fromCodePoint(0x1f320),
            EmojiObject.fromChar((char) 0x2b50),
            EmojiObject.fromChar((char) 0x2600),
            EmojiObject.fromChar((char) 0x26c5),
            EmojiObject.fromChar((char) 0x2601),
            EmojiObject.fromChar((char) 0x26a1),
            EmojiObject.fromChar((char) 0x2614),
            EmojiObject.fromChar((char) 0x2744),
            EmojiObject.fromChar((char) 0x26c4),
            EmojiObject.fromCodePoint(0x1f300),
            EmojiObject.fromCodePoint(0x1f301),
            EmojiObject.fromCodePoint(0x1f308),
            EmojiObject.fromCodePoint(0x1f30a),
    };

    public static final EmojiObject[] DATA_OBJECTS = new EmojiObject[]{
            EmojiObject.fromCodePoint(0x1f38d),
            EmojiObject.fromCodePoint(0x1f49d),
            EmojiObject.fromCodePoint(0x1f38e),
            EmojiObject.fromCodePoint(0x1f392),
            EmojiObject.fromCodePoint(0x1f393),
            EmojiObject.fromCodePoint(0x1f38f),
            EmojiObject.fromCodePoint(0x1f386),
            EmojiObject.fromCodePoint(0x1f387),
            EmojiObject.fromCodePoint(0x1f390),
            EmojiObject.fromCodePoint(0x1f391),
            EmojiObject.fromCodePoint(0x1f383),
            EmojiObject.fromCodePoint(0x1f47b),
            EmojiObject.fromCodePoint(0x1f385),
            EmojiObject.fromCodePoint(0x1f384),
            EmojiObject.fromCodePoint(0x1f381),
            EmojiObject.fromCodePoint(0x1f38b),
            EmojiObject.fromCodePoint(0x1f389),
            EmojiObject.fromCodePoint(0x1f38a),
            EmojiObject.fromCodePoint(0x1f388),
            EmojiObject.fromCodePoint(0x1f38c),
            EmojiObject.fromCodePoint(0x1f52e),
            EmojiObject.fromCodePoint(0x1f3a5),
            EmojiObject.fromCodePoint(0x1f4f7),
            EmojiObject.fromCodePoint(0x1f4f9),
            EmojiObject.fromCodePoint(0x1f4fc),
            EmojiObject.fromCodePoint(0x1f4bf),
            EmojiObject.fromCodePoint(0x1f4c0),
            EmojiObject.fromCodePoint(0x1f4bd),
            EmojiObject.fromCodePoint(0x1f4be),
            EmojiObject.fromCodePoint(0x1f4bb),
            EmojiObject.fromCodePoint(0x1f4f1),
            EmojiObject.fromChar((char) 0x260e),
            EmojiObject.fromCodePoint(0x1f4de),
            EmojiObject.fromCodePoint(0x1f4df),
            EmojiObject.fromCodePoint(0x1f4e0),
            EmojiObject.fromCodePoint(0x1f4e1),
            EmojiObject.fromCodePoint(0x1f4fa),
            EmojiObject.fromCodePoint(0x1f4fb),
            EmojiObject.fromCodePoint(0x1f508),
            EmojiObject.fromCodePoint(0x1f509),
            EmojiObject.fromCodePoint(0x1f50a),
            EmojiObject.fromCodePoint(0x1f507),
            EmojiObject.fromCodePoint(0x1f514),
            EmojiObject.fromCodePoint(0x1f515),
            EmojiObject.fromCodePoint(0x1f4e2),
            EmojiObject.fromCodePoint(0x1f4e3),
            EmojiObject.fromChar((char) 0x23f3),
            EmojiObject.fromChar((char) 0x231b),
            EmojiObject.fromChar((char) 0x23f0),
            EmojiObject.fromChar((char) 0x231a),
            EmojiObject.fromCodePoint(0x1f513),
            EmojiObject.fromCodePoint(0x1f512),
            EmojiObject.fromCodePoint(0x1f50f),
            EmojiObject.fromCodePoint(0x1f510),
            EmojiObject.fromCodePoint(0x1f511),
            EmojiObject.fromCodePoint(0x1f50e),
            EmojiObject.fromCodePoint(0x1f4a1),
            EmojiObject.fromCodePoint(0x1f526),
            EmojiObject.fromCodePoint(0x1f506),
            EmojiObject.fromCodePoint(0x1f505),
            EmojiObject.fromCodePoint(0x1f50c),
            EmojiObject.fromCodePoint(0x1f50b),
            EmojiObject.fromCodePoint(0x1f50d),
            EmojiObject.fromCodePoint(0x1f6c1),
            EmojiObject.fromCodePoint(0x1f6c0),
            EmojiObject.fromCodePoint(0x1f6bf),
            EmojiObject.fromCodePoint(0x1f6bd),
            EmojiObject.fromCodePoint(0x1f527),
            EmojiObject.fromCodePoint(0x1f529),
            EmojiObject.fromCodePoint(0x1f528),
            EmojiObject.fromCodePoint(0x1f6aa),
            EmojiObject.fromCodePoint(0x1f6ac),
            EmojiObject.fromCodePoint(0x1f4a3),
            EmojiObject.fromCodePoint(0x1f52b),
            EmojiObject.fromCodePoint(0x1f52a),
            EmojiObject.fromCodePoint(0x1f48a),
            EmojiObject.fromCodePoint(0x1f489),
            EmojiObject.fromCodePoint(0x1f4b0),
            EmojiObject.fromCodePoint(0x1f4b4),
            EmojiObject.fromCodePoint(0x1f4b5),
            EmojiObject.fromCodePoint(0x1f4b7),
            EmojiObject.fromCodePoint(0x1f4b6),
            EmojiObject.fromCodePoint(0x1f4b3),
            EmojiObject.fromCodePoint(0x1f4b8),
            EmojiObject.fromCodePoint(0x1f4f2),
            EmojiObject.fromCodePoint(0x1f4e7),
            EmojiObject.fromCodePoint(0x1f4e5),
            EmojiObject.fromCodePoint(0x1f4e4),
            EmojiObject.fromChar((char) 0x2709),
            EmojiObject.fromCodePoint(0x1f4e9),
            EmojiObject.fromCodePoint(0x1f4e8),
            EmojiObject.fromCodePoint(0x1f4ef),
            EmojiObject.fromCodePoint(0x1f4eb),
            EmojiObject.fromCodePoint(0x1f4ea),
            EmojiObject.fromCodePoint(0x1f4ec),
            EmojiObject.fromCodePoint(0x1f4ed),
            EmojiObject.fromCodePoint(0x1f4ee),
            EmojiObject.fromCodePoint(0x1f4e6),
            EmojiObject.fromCodePoint(0x1f4dd),
            EmojiObject.fromCodePoint(0x1f4c4),
            EmojiObject.fromCodePoint(0x1f4c3),
            EmojiObject.fromCodePoint(0x1f4d1),
            EmojiObject.fromCodePoint(0x1f4ca),
            EmojiObject.fromCodePoint(0x1f4c8),
            EmojiObject.fromCodePoint(0x1f4c9),
            EmojiObject.fromCodePoint(0x1f4dc),
            EmojiObject.fromCodePoint(0x1f4cb),
            EmojiObject.fromCodePoint(0x1f4c5),
            EmojiObject.fromCodePoint(0x1f4c6),
            EmojiObject.fromCodePoint(0x1f4c7),
            EmojiObject.fromCodePoint(0x1f4c1),
            EmojiObject.fromCodePoint(0x1f4c2),
            EmojiObject.fromChar((char) 0x2702),
            EmojiObject.fromCodePoint(0x1f4cc),
            EmojiObject.fromCodePoint(0x1f4ce),
            EmojiObject.fromChar((char) 0x2712),
            EmojiObject.fromChar((char) 0x270f),
            EmojiObject.fromCodePoint(0x1f4cf),
            EmojiObject.fromCodePoint(0x1f4d0),
            EmojiObject.fromCodePoint(0x1f4d5),
            EmojiObject.fromCodePoint(0x1f4d7),
            EmojiObject.fromCodePoint(0x1f4d8),
            EmojiObject.fromCodePoint(0x1f4d9),
            EmojiObject.fromCodePoint(0x1f4d3),
            EmojiObject.fromCodePoint(0x1f4d4),
            EmojiObject.fromCodePoint(0x1f4d2),
            EmojiObject.fromCodePoint(0x1f4da),
            EmojiObject.fromCodePoint(0x1f4d6),
            EmojiObject.fromCodePoint(0x1f516),
            EmojiObject.fromCodePoint(0x1f4db),
            EmojiObject.fromCodePoint(0x1f52c),
            EmojiObject.fromCodePoint(0x1f52d),
            EmojiObject.fromCodePoint(0x1f4f0),
            EmojiObject.fromCodePoint(0x1f3a8),
            EmojiObject.fromCodePoint(0x1f3ac),
            EmojiObject.fromCodePoint(0x1f3a4),
            EmojiObject.fromCodePoint(0x1f3a7),
            EmojiObject.fromCodePoint(0x1f3bc),
            EmojiObject.fromCodePoint(0x1f3b5),
            EmojiObject.fromCodePoint(0x1f3b6),
            EmojiObject.fromCodePoint(0x1f3b9),
            EmojiObject.fromCodePoint(0x1f3bb),
            EmojiObject.fromCodePoint(0x1f3ba),
            EmojiObject.fromCodePoint(0x1f3b7),
            EmojiObject.fromCodePoint(0x1f3b8),
            EmojiObject.fromCodePoint(0x1f47e),
            EmojiObject.fromCodePoint(0x1f3ae),
            EmojiObject.fromCodePoint(0x1f0cf),
            EmojiObject.fromCodePoint(0x1f3b4),
            EmojiObject.fromCodePoint(0x1f004),
            EmojiObject.fromCodePoint(0x1f3b2),
            EmojiObject.fromCodePoint(0x1f3af),
            EmojiObject.fromCodePoint(0x1f3c8),
            EmojiObject.fromCodePoint(0x1f3c0),
            EmojiObject.fromChar((char) 0x26bd),
            EmojiObject.fromChar((char) 0x26be),
            EmojiObject.fromCodePoint(0x1f3be),
            EmojiObject.fromCodePoint(0x1f3b1),
            EmojiObject.fromCodePoint(0x1f3c9),
            EmojiObject.fromCodePoint(0x1f3b3),
            EmojiObject.fromChar((char) 0x26f3),
            EmojiObject.fromCodePoint(0x1f6b5),
            EmojiObject.fromCodePoint(0x1f6b4),
            EmojiObject.fromCodePoint(0x1f3c1),
            EmojiObject.fromCodePoint(0x1f3c7),
            EmojiObject.fromCodePoint(0x1f3c6),
            EmojiObject.fromCodePoint(0x1f3bf),
            EmojiObject.fromCodePoint(0x1f3c2),
            EmojiObject.fromCodePoint(0x1f3ca),
            EmojiObject.fromCodePoint(0x1f3c4),
            EmojiObject.fromCodePoint(0x1f3a3),
            EmojiObject.fromChar((char) 0x2615),
            EmojiObject.fromCodePoint(0x1f375),
            EmojiObject.fromCodePoint(0x1f376),
            EmojiObject.fromCodePoint(0x1f37c),
            EmojiObject.fromCodePoint(0x1f37a),
            EmojiObject.fromCodePoint(0x1f37b),
            EmojiObject.fromCodePoint(0x1f378),
            EmojiObject.fromCodePoint(0x1f379),
            EmojiObject.fromCodePoint(0x1f377),
            EmojiObject.fromCodePoint(0x1f374),
            EmojiObject.fromCodePoint(0x1f355),
            EmojiObject.fromCodePoint(0x1f354),
            EmojiObject.fromCodePoint(0x1f35f),
            EmojiObject.fromCodePoint(0x1f357),
            EmojiObject.fromCodePoint(0x1f356),
            EmojiObject.fromCodePoint(0x1f35d),
            EmojiObject.fromCodePoint(0x1f35b),
            EmojiObject.fromCodePoint(0x1f364),
            EmojiObject.fromCodePoint(0x1f371),
            EmojiObject.fromCodePoint(0x1f363),
            EmojiObject.fromCodePoint(0x1f365),
            EmojiObject.fromCodePoint(0x1f359),
            EmojiObject.fromCodePoint(0x1f358),
            EmojiObject.fromCodePoint(0x1f35a),
            EmojiObject.fromCodePoint(0x1f35c),
            EmojiObject.fromCodePoint(0x1f372),
            EmojiObject.fromCodePoint(0x1f362),
            EmojiObject.fromCodePoint(0x1f361),
            EmojiObject.fromCodePoint(0x1f373),
            EmojiObject.fromCodePoint(0x1f35e),
            EmojiObject.fromCodePoint(0x1f369),
            EmojiObject.fromCodePoint(0x1f36e),
            EmojiObject.fromCodePoint(0x1f366),
            EmojiObject.fromCodePoint(0x1f368),
            EmojiObject.fromCodePoint(0x1f367),
            EmojiObject.fromCodePoint(0x1f382),
            EmojiObject.fromCodePoint(0x1f370),
            EmojiObject.fromCodePoint(0x1f36a),
            EmojiObject.fromCodePoint(0x1f36b),
            EmojiObject.fromCodePoint(0x1f36c),
            EmojiObject.fromCodePoint(0x1f36d),
            EmojiObject.fromCodePoint(0x1f36f),
            EmojiObject.fromCodePoint(0x1f34e),
            EmojiObject.fromCodePoint(0x1f34f),
            EmojiObject.fromCodePoint(0x1f34a),
            EmojiObject.fromCodePoint(0x1f34b),
            EmojiObject.fromCodePoint(0x1f352),
            EmojiObject.fromCodePoint(0x1f347),
            EmojiObject.fromCodePoint(0x1f349),
            EmojiObject.fromCodePoint(0x1f353),
            EmojiObject.fromCodePoint(0x1f351),
            EmojiObject.fromCodePoint(0x1f348),
            EmojiObject.fromCodePoint(0x1f34c),
            EmojiObject.fromCodePoint(0x1f350),
            EmojiObject.fromCodePoint(0x1f34d),
            EmojiObject.fromCodePoint(0x1f360),
            EmojiObject.fromCodePoint(0x1f346),
            EmojiObject.fromCodePoint(0x1f345),
            EmojiObject.fromCodePoint(0x1f33d),
    };

    public static final EmojiObject[] DATA_PEOPLE = new EmojiObject[]{
            EmojiObject.fromCodePoint(0x1f604),
            EmojiObject.fromCodePoint(0x1f603),
            EmojiObject.fromCodePoint(0x1f600),
            EmojiObject.fromCodePoint(0x1f60a),
            EmojiObject.fromChar((char) 0x263a),
            EmojiObject.fromCodePoint(0x1f609),
            EmojiObject.fromCodePoint(0x1f60d),
            EmojiObject.fromCodePoint(0x1f618),
            EmojiObject.fromCodePoint(0x1f61a),
            EmojiObject.fromCodePoint(0x1f617),
            EmojiObject.fromCodePoint(0x1f619),
            EmojiObject.fromCodePoint(0x1f61c),
            EmojiObject.fromCodePoint(0x1f61d),
            EmojiObject.fromCodePoint(0x1f61b),
            EmojiObject.fromCodePoint(0x1f633),
            EmojiObject.fromCodePoint(0x1f601),
            EmojiObject.fromCodePoint(0x1f614),
            EmojiObject.fromCodePoint(0x1f60c),
            EmojiObject.fromCodePoint(0x1f612),
            EmojiObject.fromCodePoint(0x1f61e),
            EmojiObject.fromCodePoint(0x1f623),
            EmojiObject.fromCodePoint(0x1f622),
            EmojiObject.fromCodePoint(0x1f602),
            EmojiObject.fromCodePoint(0x1f62d),
            EmojiObject.fromCodePoint(0x1f62a),
            EmojiObject.fromCodePoint(0x1f625),
            EmojiObject.fromCodePoint(0x1f630),
            EmojiObject.fromCodePoint(0x1f605),
            EmojiObject.fromCodePoint(0x1f613),
            EmojiObject.fromCodePoint(0x1f629),
            EmojiObject.fromCodePoint(0x1f62b),
            EmojiObject.fromCodePoint(0x1f628),
            EmojiObject.fromCodePoint(0x1f631),
            EmojiObject.fromCodePoint(0x1f620),
            EmojiObject.fromCodePoint(0x1f621),
            EmojiObject.fromCodePoint(0x1f624),
            EmojiObject.fromCodePoint(0x1f616),
            EmojiObject.fromCodePoint(0x1f606),
            EmojiObject.fromCodePoint(0x1f60b),
            EmojiObject.fromCodePoint(0x1f637),
            EmojiObject.fromCodePoint(0x1f60e),
            EmojiObject.fromCodePoint(0x1f634),
            EmojiObject.fromCodePoint(0x1f635),
            EmojiObject.fromCodePoint(0x1f632),
            EmojiObject.fromCodePoint(0x1f61f),
            EmojiObject.fromCodePoint(0x1f626),
            EmojiObject.fromCodePoint(0x1f627),
            EmojiObject.fromCodePoint(0x1f608),
            EmojiObject.fromCodePoint(0x1f47f),
            EmojiObject.fromCodePoint(0x1f62e),
            EmojiObject.fromCodePoint(0x1f62c),
            EmojiObject.fromCodePoint(0x1f610),
            EmojiObject.fromCodePoint(0x1f615),
            EmojiObject.fromCodePoint(0x1f62f),
            EmojiObject.fromCodePoint(0x1f636),
            EmojiObject.fromCodePoint(0x1f607),
            EmojiObject.fromCodePoint(0x1f60f),
            EmojiObject.fromCodePoint(0x1f611),
            EmojiObject.fromCodePoint(0x1f472),
            EmojiObject.fromCodePoint(0x1f473),
            EmojiObject.fromCodePoint(0x1f46e),
            EmojiObject.fromCodePoint(0x1f477),
            EmojiObject.fromCodePoint(0x1f482),
            EmojiObject.fromCodePoint(0x1f476),
            EmojiObject.fromCodePoint(0x1f466),
            EmojiObject.fromCodePoint(0x1f467),
            EmojiObject.fromCodePoint(0x1f468),
            EmojiObject.fromCodePoint(0x1f469),
            EmojiObject.fromCodePoint(0x1f474),
            EmojiObject.fromCodePoint(0x1f475),
            EmojiObject.fromCodePoint(0x1f471),
            EmojiObject.fromCodePoint(0x1f47c),
            EmojiObject.fromCodePoint(0x1f478),
            EmojiObject.fromCodePoint(0x1f63a),
            EmojiObject.fromCodePoint(0x1f638),
            EmojiObject.fromCodePoint(0x1f63b),
            EmojiObject.fromCodePoint(0x1f63d),
            EmojiObject.fromCodePoint(0x1f63c),
            EmojiObject.fromCodePoint(0x1f640),
            EmojiObject.fromCodePoint(0x1f63f),
            EmojiObject.fromCodePoint(0x1f639),
            EmojiObject.fromCodePoint(0x1f63e),
            EmojiObject.fromCodePoint(0x1f479),
            EmojiObject.fromCodePoint(0x1f47a),
            EmojiObject.fromCodePoint(0x1f648),
            EmojiObject.fromCodePoint(0x1f649),
            EmojiObject.fromCodePoint(0x1f64a),
            EmojiObject.fromCodePoint(0x1f480),
            EmojiObject.fromCodePoint(0x1f47d),
            EmojiObject.fromCodePoint(0x1f4a9),
            EmojiObject.fromCodePoint(0x1f525),
            EmojiObject.fromChar((char) 0x2728),
            EmojiObject.fromCodePoint(0x1f31f),
            EmojiObject.fromCodePoint(0x1f4ab),
            EmojiObject.fromCodePoint(0x1f4a5),
            EmojiObject.fromCodePoint(0x1f4a2),
            EmojiObject.fromCodePoint(0x1f4a6),
            EmojiObject.fromCodePoint(0x1f4a7),
            EmojiObject.fromCodePoint(0x1f4a4),
            EmojiObject.fromCodePoint(0x1f4a8),
            EmojiObject.fromCodePoint(0x1f442),
            EmojiObject.fromCodePoint(0x1f440),
            EmojiObject.fromCodePoint(0x1f443),
            EmojiObject.fromCodePoint(0x1f445),
            EmojiObject.fromCodePoint(0x1f444),
            EmojiObject.fromCodePoint(0x1f44d),
            EmojiObject.fromCodePoint(0x1f44e),
            EmojiObject.fromCodePoint(0x1f44c),
            EmojiObject.fromCodePoint(0x1f44a),
            EmojiObject.fromChar((char) 0x270a),
            EmojiObject.fromChar((char) 0x270c),
            EmojiObject.fromCodePoint(0x1f44b),
            EmojiObject.fromChar((char) 0x270b),
            EmojiObject.fromCodePoint(0x1f450),
            EmojiObject.fromCodePoint(0x1f446),
            EmojiObject.fromCodePoint(0x1f447),
            EmojiObject.fromCodePoint(0x1f449),
            EmojiObject.fromCodePoint(0x1f448),
            EmojiObject.fromCodePoint(0x1f64c),
            EmojiObject.fromCodePoint(0x1f64f),
            EmojiObject.fromChar((char) 0x261d),
            EmojiObject.fromCodePoint(0x1f44f),
            EmojiObject.fromCodePoint(0x1f4aa),
            EmojiObject.fromCodePoint(0x1f6b6),
            EmojiObject.fromCodePoint(0x1f3c3),
            EmojiObject.fromCodePoint(0x1f483),
            EmojiObject.fromCodePoint(0x1f46b),
            EmojiObject.fromCodePoint(0x1f46a),
            EmojiObject.fromCodePoint(0x1f46c),
            EmojiObject.fromCodePoint(0x1f46d),
            EmojiObject.fromCodePoint(0x1f48f),
            EmojiObject.fromCodePoint(0x1f491),
            EmojiObject.fromCodePoint(0x1f46f),
            EmojiObject.fromCodePoint(0x1f646),
            EmojiObject.fromCodePoint(0x1f645),
            EmojiObject.fromCodePoint(0x1f481),
            EmojiObject.fromCodePoint(0x1f64b),
            EmojiObject.fromCodePoint(0x1f486),
            EmojiObject.fromCodePoint(0x1f487),
            EmojiObject.fromCodePoint(0x1f485),
            EmojiObject.fromCodePoint(0x1f470),
            EmojiObject.fromCodePoint(0x1f64e),
            EmojiObject.fromCodePoint(0x1f64d),
            EmojiObject.fromCodePoint(0x1f647),
            EmojiObject.fromCodePoint(0x1f3a9),
            EmojiObject.fromCodePoint(0x1f451),
            EmojiObject.fromCodePoint(0x1f452),
            EmojiObject.fromCodePoint(0x1f45f),
            EmojiObject.fromCodePoint(0x1f45e),
            EmojiObject.fromCodePoint(0x1f461),
            EmojiObject.fromCodePoint(0x1f460),
            EmojiObject.fromCodePoint(0x1f462),
            EmojiObject.fromCodePoint(0x1f455),
            EmojiObject.fromCodePoint(0x1f454),
            EmojiObject.fromCodePoint(0x1f45a),
            EmojiObject.fromCodePoint(0x1f457),
            EmojiObject.fromCodePoint(0x1f3bd),
            EmojiObject.fromCodePoint(0x1f456),
            EmojiObject.fromCodePoint(0x1f458),
            EmojiObject.fromCodePoint(0x1f459),
            EmojiObject.fromCodePoint(0x1f4bc),
            EmojiObject.fromCodePoint(0x1f45c),
            EmojiObject.fromCodePoint(0x1f45d),
            EmojiObject.fromCodePoint(0x1f45b),
            EmojiObject.fromCodePoint(0x1f453),
            EmojiObject.fromCodePoint(0x1f380),
            EmojiObject.fromCodePoint(0x1f302),
            EmojiObject.fromCodePoint(0x1f484),
            EmojiObject.fromCodePoint(0x1f49b),
            EmojiObject.fromCodePoint(0x1f499),
            EmojiObject.fromCodePoint(0x1f49c),
            EmojiObject.fromCodePoint(0x1f49a),
            EmojiObject.fromChar((char) 0x2764),
            EmojiObject.fromCodePoint(0x1f494),
            EmojiObject.fromCodePoint(0x1f497),
            EmojiObject.fromCodePoint(0x1f493),
            EmojiObject.fromCodePoint(0x1f495),
            EmojiObject.fromCodePoint(0x1f496),
            EmojiObject.fromCodePoint(0x1f49e),
            EmojiObject.fromCodePoint(0x1f498),
            EmojiObject.fromCodePoint(0x1f48c),
            EmojiObject.fromCodePoint(0x1f48b),
            EmojiObject.fromCodePoint(0x1f48d),
            EmojiObject.fromCodePoint(0x1f48e),
            EmojiObject.fromCodePoint(0x1f464),
            EmojiObject.fromCodePoint(0x1f465),
            EmojiObject.fromCodePoint(0x1f4ac),
            EmojiObject.fromCodePoint(0x1f463),
            EmojiObject.fromCodePoint(0x1f4ad),
    };

    public static final EmojiObject[] DATA_PLACES = new EmojiObject[]{
            EmojiObject.fromCodePoint(0x1f3e0),
            EmojiObject.fromCodePoint(0x1f3e1),
            EmojiObject.fromCodePoint(0x1f3eb),
            EmojiObject.fromCodePoint(0x1f3e2),
            EmojiObject.fromCodePoint(0x1f3e3),
            EmojiObject.fromCodePoint(0x1f3e5),
            EmojiObject.fromCodePoint(0x1f3e6),
            EmojiObject.fromCodePoint(0x1f3ea),
            EmojiObject.fromCodePoint(0x1f3e9),
            EmojiObject.fromCodePoint(0x1f3e8),
            EmojiObject.fromCodePoint(0x1f492),
            EmojiObject.fromChar((char) 0x26ea),
            EmojiObject.fromCodePoint(0x1f3ec),
            EmojiObject.fromCodePoint(0x1f3e4),
            EmojiObject.fromCodePoint(0x1f307),
            EmojiObject.fromCodePoint(0x1f306),
            EmojiObject.fromCodePoint(0x1f3ef),
            EmojiObject.fromCodePoint(0x1f3f0),
            EmojiObject.fromChar((char) 0x26fa),
            EmojiObject.fromCodePoint(0x1f3ed),
            EmojiObject.fromCodePoint(0x1f5fc),
            EmojiObject.fromCodePoint(0x1f5fe),
            EmojiObject.fromCodePoint(0x1f5fb),
            EmojiObject.fromCodePoint(0x1f304),
            EmojiObject.fromCodePoint(0x1f305),
            EmojiObject.fromCodePoint(0x1f303),
            EmojiObject.fromCodePoint(0x1f5fd),
            EmojiObject.fromCodePoint(0x1f309),
            EmojiObject.fromCodePoint(0x1f3a0),
            EmojiObject.fromCodePoint(0x1f3a1),
            EmojiObject.fromChar((char) 0x26f2),
            EmojiObject.fromCodePoint(0x1f3a2),
            EmojiObject.fromCodePoint(0x1f6a2),
            EmojiObject.fromChar((char) 0x26f5),
            EmojiObject.fromCodePoint(0x1f6a4),
            EmojiObject.fromCodePoint(0x1f6a3),
            EmojiObject.fromChar((char) 0x2693),
            EmojiObject.fromCodePoint(0x1f680),
            EmojiObject.fromChar((char) 0x2708),
            EmojiObject.fromCodePoint(0x1f4ba),
            EmojiObject.fromCodePoint(0x1f681),
            EmojiObject.fromCodePoint(0x1f682),
            EmojiObject.fromCodePoint(0x1f68a),
            EmojiObject.fromCodePoint(0x1f689),
            EmojiObject.fromCodePoint(0x1f69e),
            EmojiObject.fromCodePoint(0x1f686),
            EmojiObject.fromCodePoint(0x1f684),
            EmojiObject.fromCodePoint(0x1f685),
            EmojiObject.fromCodePoint(0x1f688),
            EmojiObject.fromCodePoint(0x1f687),
            EmojiObject.fromCodePoint(0x1f69d),
            EmojiObject.fromCodePoint(0x1f68b),
            EmojiObject.fromCodePoint(0x1f683),
            EmojiObject.fromCodePoint(0x1f68e),
            EmojiObject.fromCodePoint(0x1f68c),
            EmojiObject.fromCodePoint(0x1f68d),
            EmojiObject.fromCodePoint(0x1f699),
            EmojiObject.fromCodePoint(0x1f698),
            EmojiObject.fromCodePoint(0x1f697),
            EmojiObject.fromCodePoint(0x1f695),
            EmojiObject.fromCodePoint(0x1f696),
            EmojiObject.fromCodePoint(0x1f69b),
            EmojiObject.fromCodePoint(0x1f69a),
            EmojiObject.fromCodePoint(0x1f6a8),
            EmojiObject.fromCodePoint(0x1f693),
            EmojiObject.fromCodePoint(0x1f694),
            EmojiObject.fromCodePoint(0x1f692),
            EmojiObject.fromCodePoint(0x1f691),
            EmojiObject.fromCodePoint(0x1f690),
            EmojiObject.fromCodePoint(0x1f6b2),
            EmojiObject.fromCodePoint(0x1f6a1),
            EmojiObject.fromCodePoint(0x1f69f),
            EmojiObject.fromCodePoint(0x1f6a0),
            EmojiObject.fromCodePoint(0x1f69c),
            EmojiObject.fromCodePoint(0x1f488),
            EmojiObject.fromCodePoint(0x1f68f),
            EmojiObject.fromCodePoint(0x1f3ab),
            EmojiObject.fromCodePoint(0x1f6a6),
            EmojiObject.fromCodePoint(0x1f6a5),
            EmojiObject.fromChar((char) 0x26a0),
            EmojiObject.fromCodePoint(0x1f6a7),
            EmojiObject.fromCodePoint(0x1f530),
            EmojiObject.fromChar((char) 0x26fd),
            EmojiObject.fromCodePoint(0x1f3ee),
            EmojiObject.fromCodePoint(0x1f3b0),
            EmojiObject.fromChar((char) 0x2668),
            EmojiObject.fromCodePoint(0x1f5ff),
            EmojiObject.fromCodePoint(0x1f3aa),
            EmojiObject.fromCodePoint(0x1f3ad),
            EmojiObject.fromCodePoint(0x1f4cd),
            EmojiObject.fromCodePoint(0x1f6a9),
            EmojiObject.fromChars("\ud83c\uddef\ud83c\uddf5"),
            EmojiObject.fromChars("\ud83c\uddf0\ud83c\uddf7"),
            EmojiObject.fromChars("\ud83c\udde9\ud83c\uddea"),
            EmojiObject.fromChars("\ud83c\udde8\ud83c\uddf3"),
            EmojiObject.fromChars("\ud83c\uddfa\ud83c\uddf8"),
            EmojiObject.fromChars("\ud83c\uddeb\ud83c\uddf7"),
            EmojiObject.fromChars("\ud83c\uddea\ud83c\uddf8"),
            EmojiObject.fromChars("\ud83c\uddee\ud83c\uddf9"),
            EmojiObject.fromChars("\ud83c\uddf7\ud83c\uddfa"),
            EmojiObject.fromChars("\ud83c\uddec\ud83c\udde7"),
    };

    public static final EmojiObject[] DATA_SYMBOLS = new EmojiObject[]{
            EmojiObject.fromChars("\u0031\u20e3"),
            EmojiObject.fromChars("\u0032\u20e3"),
            EmojiObject.fromChars("\u0033\u20e3"),
            EmojiObject.fromChars("\u0034\u20e3"),
            EmojiObject.fromChars("\u0035\u20e3"),
            EmojiObject.fromChars("\u0036\u20e3"),
            EmojiObject.fromChars("\u0037\u20e3"),
            EmojiObject.fromChars("\u0038\u20e3"),
            EmojiObject.fromChars("\u0039\u20e3"),
            EmojiObject.fromChars("\u0030\u20e3"),
            EmojiObject.fromCodePoint(0x1f51f),
            EmojiObject.fromCodePoint(0x1f522),
            EmojiObject.fromChars("\u0023\u20e3"),
            EmojiObject.fromCodePoint(0x1f523),
            EmojiObject.fromChar((char) 0x2b06),
            EmojiObject.fromChar((char) 0x2b07),
            EmojiObject.fromChar((char) 0x2b05),
            EmojiObject.fromChar((char) 0x27a1),
            EmojiObject.fromCodePoint(0x1f520),
            EmojiObject.fromCodePoint(0x1f521),
            EmojiObject.fromCodePoint(0x1f524),
            EmojiObject.fromChar((char) 0x2197),
            EmojiObject.fromChar((char) 0x2196),
            EmojiObject.fromChar((char) 0x2198),
            EmojiObject.fromChar((char) 0x2199),
            EmojiObject.fromChar((char) 0x2194),
            EmojiObject.fromChar((char) 0x2195),
            EmojiObject.fromCodePoint(0x1f504),
            EmojiObject.fromChar((char) 0x25c0),
            EmojiObject.fromChar((char) 0x25b6),
            EmojiObject.fromCodePoint(0x1f53c),
            EmojiObject.fromCodePoint(0x1f53d),
            EmojiObject.fromChar((char) 0x21a9),
            EmojiObject.fromChar((char) 0x21aa),
            EmojiObject.fromChar((char) 0x2139),
            EmojiObject.fromChar((char) 0x23ea),
            EmojiObject.fromChar((char) 0x23e9),
            EmojiObject.fromChar((char) 0x23eb),
            EmojiObject.fromChar((char) 0x23ec),
            EmojiObject.fromChar((char) 0x2935),
            EmojiObject.fromChar((char) 0x2934),
            EmojiObject.fromCodePoint(0x1f197),
            EmojiObject.fromCodePoint(0x1f500),
            EmojiObject.fromCodePoint(0x1f501),
            EmojiObject.fromCodePoint(0x1f502),
            EmojiObject.fromCodePoint(0x1f195),
            EmojiObject.fromCodePoint(0x1f199),
            EmojiObject.fromCodePoint(0x1f192),
            EmojiObject.fromCodePoint(0x1f193),
            EmojiObject.fromCodePoint(0x1f196),
            EmojiObject.fromCodePoint(0x1f4f6),
            EmojiObject.fromCodePoint(0x1f3a6),
            EmojiObject.fromCodePoint(0x1f201),
            EmojiObject.fromCodePoint(0x1f22f),
            EmojiObject.fromCodePoint(0x1f233),
            EmojiObject.fromCodePoint(0x1f235),
            EmojiObject.fromCodePoint(0x1f234),
            EmojiObject.fromCodePoint(0x1f232),
            EmojiObject.fromCodePoint(0x1f250),
            EmojiObject.fromCodePoint(0x1f239),
            EmojiObject.fromCodePoint(0x1f23a),
            EmojiObject.fromCodePoint(0x1f236),
            EmojiObject.fromCodePoint(0x1f21a),
            EmojiObject.fromCodePoint(0x1f6bb),
            EmojiObject.fromCodePoint(0x1f6b9),
            EmojiObject.fromCodePoint(0x1f6ba),
            EmojiObject.fromCodePoint(0x1f6bc),
            EmojiObject.fromCodePoint(0x1f6be),
            EmojiObject.fromCodePoint(0x1f6b0),
            EmojiObject.fromCodePoint(0x1f6ae),
            EmojiObject.fromCodePoint(0x1f17f),
            EmojiObject.fromChar((char) 0x267f),
            EmojiObject.fromCodePoint(0x1f6ad),
            EmojiObject.fromCodePoint(0x1f237),
            EmojiObject.fromCodePoint(0x1f238),
            EmojiObject.fromCodePoint(0x1f202),
            EmojiObject.fromChar((char) 0x24c2),
            EmojiObject.fromCodePoint(0x1f6c2),
            EmojiObject.fromCodePoint(0x1f6c4),
            EmojiObject.fromCodePoint(0x1f6c5),
            EmojiObject.fromCodePoint(0x1f6c3),
            EmojiObject.fromCodePoint(0x1f251),
            EmojiObject.fromChar((char) 0x3299),
            EmojiObject.fromChar((char) 0x3297),
            EmojiObject.fromCodePoint(0x1f191),
            EmojiObject.fromCodePoint(0x1f198),
            EmojiObject.fromCodePoint(0x1f194),
            EmojiObject.fromCodePoint(0x1f6ab),
            EmojiObject.fromCodePoint(0x1f51e),
            EmojiObject.fromCodePoint(0x1f4f5),
            EmojiObject.fromCodePoint(0x1f6af),
            EmojiObject.fromCodePoint(0x1f6b1),
            EmojiObject.fromCodePoint(0x1f6b3),
            EmojiObject.fromCodePoint(0x1f6b7),
            EmojiObject.fromCodePoint(0x1f6b8),
            EmojiObject.fromChar((char) 0x26d4),
            EmojiObject.fromChar((char) 0x2733),
            EmojiObject.fromChar((char) 0x2747),
            EmojiObject.fromChar((char) 0x274e),
            EmojiObject.fromChar((char) 0x2705),
            EmojiObject.fromChar((char) 0x2734),
            EmojiObject.fromCodePoint(0x1f49f),
            EmojiObject.fromCodePoint(0x1f19a),
            EmojiObject.fromCodePoint(0x1f4f3),
            EmojiObject.fromCodePoint(0x1f4f4),
            EmojiObject.fromCodePoint(0x1f170),
            EmojiObject.fromCodePoint(0x1f171),
            EmojiObject.fromCodePoint(0x1f18e),
            EmojiObject.fromCodePoint(0x1f17e),
            EmojiObject.fromCodePoint(0x1f4a0),
            EmojiObject.fromChar((char) 0x27bf),
            EmojiObject.fromChar((char) 0x267b),
            EmojiObject.fromChar((char) 0x2648),
            EmojiObject.fromChar((char) 0x2649),
            EmojiObject.fromChar((char) 0x264a),
            EmojiObject.fromChar((char) 0x264b),
            EmojiObject.fromChar((char) 0x264c),
            EmojiObject.fromChar((char) 0x264d),
            EmojiObject.fromChar((char) 0x264e),
            EmojiObject.fromChar((char) 0x264f),
            EmojiObject.fromChar((char) 0x2650),
            EmojiObject.fromChar((char) 0x2651),
            EmojiObject.fromChar((char) 0x2652),
            EmojiObject.fromChar((char) 0x2653),
            EmojiObject.fromChar((char) 0x26ce),
            EmojiObject.fromCodePoint(0x1f52f),
            EmojiObject.fromCodePoint(0x1f3e7),
            EmojiObject.fromCodePoint(0x1f4b9),
            EmojiObject.fromCodePoint(0x1f4b2),
            EmojiObject.fromCodePoint(0x1f4b1),
            EmojiObject.fromChar((char)0x00a9),
            EmojiObject.fromChar((char)0x00ae),
            EmojiObject.fromChar((char) 0xe24e),
            EmojiObject.fromChar((char) 0xe24f),
            EmojiObject.fromChar((char) 0x2122),
            EmojiObject.fromChar((char) 0x274c),
            EmojiObject.fromChar((char) 0x203c),
            EmojiObject.fromChar((char) 0x2049),
            EmojiObject.fromChar((char) 0x2757),
            EmojiObject.fromChar((char) 0x2753),
            EmojiObject.fromChar((char) 0x2755),
            EmojiObject.fromChar((char) 0x2754),
            EmojiObject.fromChar((char) 0x2b55),
            EmojiObject.fromCodePoint(0x1f51d),
            EmojiObject.fromCodePoint(0x1f51a),
            EmojiObject.fromCodePoint(0x1f519),
            EmojiObject.fromCodePoint(0x1f51b),
            EmojiObject.fromCodePoint(0x1f51c),
            EmojiObject.fromCodePoint(0x1f503),
            EmojiObject.fromCodePoint(0x1f55b),
            EmojiObject.fromCodePoint(0x1f567),
            EmojiObject.fromCodePoint(0x1f550),
            EmojiObject.fromCodePoint(0x1f55c),
            EmojiObject.fromCodePoint(0x1f551),
            EmojiObject.fromCodePoint(0x1f55d),
            EmojiObject.fromCodePoint(0x1f552),
            EmojiObject.fromCodePoint(0x1f55e),
            EmojiObject.fromCodePoint(0x1f553),
            EmojiObject.fromCodePoint(0x1f55f),
            EmojiObject.fromCodePoint(0x1f554),
            EmojiObject.fromCodePoint(0x1f560),
            EmojiObject.fromCodePoint(0x1f555),
            EmojiObject.fromCodePoint(0x1f556),
            EmojiObject.fromCodePoint(0x1f557),
            EmojiObject.fromCodePoint(0x1f558),
            EmojiObject.fromCodePoint(0x1f559),
            EmojiObject.fromCodePoint(0x1f55a),
            EmojiObject.fromCodePoint(0x1f561),
            EmojiObject.fromCodePoint(0x1f562),
            EmojiObject.fromCodePoint(0x1f563),
            EmojiObject.fromCodePoint(0x1f564),
            EmojiObject.fromCodePoint(0x1f565),
            EmojiObject.fromCodePoint(0x1f566),
            EmojiObject.fromChar((char) 0x2716),
            EmojiObject.fromChar((char) 0x2795),
            EmojiObject.fromChar((char) 0x2796),
            EmojiObject.fromChar((char) 0x2797),
            EmojiObject.fromChar((char) 0x2660),
            EmojiObject.fromChar((char) 0x2665),
            EmojiObject.fromChar((char) 0x2663),
            EmojiObject.fromChar((char) 0x2666),
            EmojiObject.fromCodePoint(0x1f4ae),
            EmojiObject.fromCodePoint(0x1f4af),
            EmojiObject.fromChar((char) 0x2714),
            EmojiObject.fromChar((char) 0x2611),
            EmojiObject.fromCodePoint(0x1f518),
            EmojiObject.fromCodePoint(0x1f517),
            EmojiObject.fromChar((char) 0x27b0),
            EmojiObject.fromChar((char) 0x3030),
            EmojiObject.fromChar((char) 0x303d),
            EmojiObject.fromCodePoint(0x1f531),
            EmojiObject.fromChar((char) 0x25fc),
            EmojiObject.fromChar((char) 0x25fb),
            EmojiObject.fromChar((char) 0x25fe),
            EmojiObject.fromChar((char) 0x25fd),
            EmojiObject.fromChar((char) 0x25aa),
            EmojiObject.fromChar((char) 0x25ab),
            EmojiObject.fromCodePoint(0x1f53a),
            EmojiObject.fromCodePoint(0x1f532),
            EmojiObject.fromCodePoint(0x1f533),
            EmojiObject.fromChar((char) 0x26ab),
            EmojiObject.fromChar((char) 0x26aa),
            EmojiObject.fromCodePoint(0x1f534),
            EmojiObject.fromCodePoint(0x1f535),
            EmojiObject.fromCodePoint(0x1f53b),
            EmojiObject.fromChar((char) 0x2b1c),
            EmojiObject.fromChar((char) 0x2b1b),
            EmojiObject.fromCodePoint(0x1f536),
            EmojiObject.fromCodePoint(0x1f537),
            EmojiObject.fromCodePoint(0x1f538),
            EmojiObject.fromCodePoint(0x1f539),
    };
}